Обновление скрипта

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -27,9 +27,8 @@ jobs:
       run: |
         python main.py
 
-    - name: Check created files
-      run: |
-        echo "Checking for files"
-        ls -al
-        cat script_log.txt || echo "Log file not found"
-        cat flight_prices.txt || echo "Data file not found"
+ - name: Check created files
+  run: |
+    echo "Checking for files"
+    ls -al
+    cat test_file.txt || echo "Test file not found"
