Обновление скрипта

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -1,26 +1,32 @@
 name: Run Python Script
 
-on:
-  schedule:
-    - cron: '*/30 * * * *'  # Каждые 30 минут
+on: [push]
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.12'
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
 
-      - name: Install dependencies
-        run: |
-          pip install -r requirements.txt
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
 
-      - name: Run script
-        run: |
-          python main.py
+    - name: Run Python script
+      run: |
+        python your_script.py
+
+    - name: Check created files
+      run: |
+        echo "Checking for files"
+        ls -al
+        cat script_log.txt || echo "Log file not found"
+        cat flight_prices.txt || echo "Data file not found"
